name: notes_api
description: The interface and models for an API providing acces to todos.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  isar: ^2.4.0
  isar_flutter_libs: ^2.4.0
  path_provider: ^2.0.9

dev_dependencies:
  isar_generator: ^2.4.0
  build_runner: ^2.1.10

